# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(default='', max_length=100, verbose_name='Scientific Name')),
                ('cap_color', models.CharField(default='', max_length=40, verbose_name='Cap color')),
                ('cap_zoned', models.CharField(default='', max_length=40, verbose_name='Cap zoned')),
                ('cap_texture', models.CharField(default='', max_length=40, verbose_name='Cap texture')),
                ('cap_margin', models.CharField(default='', max_length=40, verbose_name='Cap margin when mature')),
                ('cap_center', models.CharField(default='', max_length=40, verbose_name='Cap center when mature')),
                ('gill_color', models.CharField(default='', max_length=40, verbose_name='Gill color')),
                ('gill_attachment', models.CharField(default='', max_length=40, verbose_name='Gill attachment')),
                ('gill_spacing', models.CharField(default='', max_length=40, verbose_name='Gill spacing')),
                ('latex_color', models.CharField(default='', max_length=40, verbose_name='Latex color')),
                ('latex_stains_gills', models.CharField(default='', max_length=40, verbose_name='Latex stains gills')),
                ('latex_changes_color', models.CharField(default='', max_length=40, verbose_name='Latex changes color when dry')),
                ('stipe_color', models.CharField(default='', max_length=40, verbose_name='Stipe color')),
                ('stipe_texture', models.CharField(default='', max_length=40, verbose_name='Stipe texture')),
                ('flesh_color', models.CharField(default='', max_length=40, verbose_name='Flesh color')),
                ('flesh_changes_color', models.CharField(default='', max_length=40, verbose_name='Flesh changes color when sliced')),
                ('spore_color', models.CharField(default='', max_length=40, verbose_name='Spore color')),
                ('odor', models.CharField(default='', max_length=40, verbose_name='Odor')),
                ('taste', models.CharField(default='', max_length=40, verbose_name='Taste')),
            ],
        ),
    ]
