# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=20)),
                ('cap_color', models.CharField(max_length=20)),
                ('cap_texture', models.CharField(max_length=20)),
                ('cap_edge', models.CharField(max_length=20)),
                ('gill_color', models.CharField(max_length=20)),
                ('latex_color', models.CharField(max_length=20)),
                ('latex_color_change', models.CharField(max_length=20)),
                ('flesh_color', models.CharField(max_length=20)),
                ('flesh_changes_color', models.CharField(max_length=20)),
                ('zonal_cap', models.CharField(max_length=20)),
                ('taste', models.CharField(max_length=20)),
                ('odor', models.CharField(max_length=20)),
                ('stripe_color', models.CharField(max_length=20)),
                ('stripe_texture', models.CharField(max_length=20)),
                ('spore_color', models.CharField(max_length=20)),
            ],
        ),
    ]
