# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='cap_color',
            field=models.CharField(max_length=20, verbose_name='Cap Color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cap_edge',
            field=models.CharField(max_length=20, verbose_name='Cap Edge'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cap_texture',
            field=models.CharField(max_length=20, verbose_name='Cap Texture'),
        ),
        migrations.AlterField(
            model_name='species',
            name='flesh_changes_color',
            field=models.CharField(max_length=20, verbose_name='Flesh Changes Color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='flesh_color',
            field=models.CharField(max_length=20, verbose_name='Flesh Color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='gill_color',
            field=models.CharField(max_length=20, verbose_name='Gill Color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='latex_color',
            field=models.CharField(max_length=20, verbose_name='Latex Color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='latex_color_change',
            field=models.CharField(max_length=20, verbose_name='Latex Color Change'),
        ),
        migrations.AlterField(
            model_name='species',
            name='odor',
            field=models.CharField(max_length=20, verbose_name='Odor'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(max_length=20, verbose_name='Scientific Name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='spore_color',
            field=models.CharField(max_length=20, verbose_name='Spore Color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='stripe_color',
            field=models.CharField(max_length=20, verbose_name='Stripe Color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='stripe_texture',
            field=models.CharField(max_length=20, verbose_name='Stripe Texture'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taste',
            field=models.CharField(max_length=20, verbose_name='Taste'),
        ),
        migrations.AlterField(
            model_name='species',
            name='zonal_cap',
            field=models.CharField(max_length=20, verbose_name='Zonal Cap'),
        ),
    ]
