# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_auto_20170726_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(default='', max_length=100, verbose_name='Scientific Name'),
        ),
    ]
