# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_auto_20170726_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='cap_center',
            field=models.CharField(default='', max_length=40, verbose_name='Cap center when mature'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cap_color',
            field=models.CharField(default='', max_length=40, verbose_name='Cap color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cap_margin',
            field=models.CharField(default='', max_length=40, verbose_name='Cap margin when mature'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cap_texture',
            field=models.CharField(default='', max_length=40, verbose_name='Cap texture'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cap_zoned',
            field=models.CharField(default='', max_length=40, verbose_name='Cap zoned'),
        ),
        migrations.AlterField(
            model_name='species',
            name='flesh_changes_color',
            field=models.CharField(default='', max_length=40, verbose_name='Flesh changes color when sliced'),
        ),
        migrations.AlterField(
            model_name='species',
            name='flesh_color',
            field=models.CharField(default='', max_length=40, verbose_name='Flesh color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='gill_attachment',
            field=models.CharField(default='', max_length=40, verbose_name='Gill attachment'),
        ),
        migrations.AlterField(
            model_name='species',
            name='gill_color',
            field=models.CharField(default='', max_length=40, verbose_name='Gill color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='gill_spacing',
            field=models.CharField(default='', max_length=40, verbose_name='Gill spacing'),
        ),
        migrations.AlterField(
            model_name='species',
            name='latex_changes_color',
            field=models.CharField(default='', max_length=40, verbose_name='Latex changes color when dry'),
        ),
        migrations.AlterField(
            model_name='species',
            name='latex_color',
            field=models.CharField(default='', max_length=40, verbose_name='Latex color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='latex_stains_gills',
            field=models.CharField(default='', max_length=40, verbose_name='Latex stains gills'),
        ),
        migrations.AlterField(
            model_name='species',
            name='spore_color',
            field=models.CharField(default='', max_length=40, verbose_name='Spore color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='stipe_color',
            field=models.CharField(default='', max_length=40, verbose_name='Stipe color'),
        ),
        migrations.AlterField(
            model_name='species',
            name='stipe_texture',
            field=models.CharField(default='', max_length=40, verbose_name='Stipe texture'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taste',
            field=models.CharField(default='', max_length=40, verbose_name='Taste'),
        ),
    ]
